#!/usr/bin/env python3
"""Generate `transform_2_0.sql` from `column_mapping_2_0.yaml`.

Run manually whenever the YAML changes:

    python backend/etl/gen_transform_2_0.py

The output SQL is committed to the repo so reviewers can diff it directly
without re-running the generator. CI may re-run this and assert the file
is unchanged (TODO: add to ci-pipeline spec if desired).

The emitted SQL assumes the three staging schemas
(``stg_main`` / ``stg_external`` / ``stg_nbs``) already exist, populated
by ``pgloader_2_0.load``. It is wrapped in a single transaction so
failures roll the whole batch back.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
MAPPING = HERE / "column_mapping_2_0.yaml"
OUTPUT = HERE / "transform_2_0.sql"

UUID_NS_FN = "uuid_ns_oid()"   # uuid-ossp; matches Python uuid.NAMESPACE_OID.


def q_ident(name: str) -> str:
    """Double-quote a Postgres identifier (table or column name)."""
    if name.startswith('"') and name.endswith('"'):
        return name
    return '"' + name.replace('"', '""') + '"'


def patient_id_expr(target_schema: str, key_cols: list[str]) -> str:
    """uuid_generate_v5(NS, '<schema>:' || key1 || '|' || key2 || ...)."""
    parts = [f"'{target_schema}:'"]
    for i, c in enumerate(key_cols):
        if i:
            parts.append("'|'")
        parts.append(f"COALESCE({q_ident(c)}::text, '')")
    return f"uuid_generate_v5({UUID_NS_FN}, {' || '.join(parts)})"


def emit_header() -> list[str]:
    return [
        "-- =========================================================================",
        "-- transform_2_0.sql — GENERATED by gen_transform_2_0.py. DO NOT EDIT BY HAND.",
        "-- Source: column_mapping_2_0.yaml",
        "--",
        "-- Reads from stg_main / stg_external / stg_nbs (populated by pgloader)",
        "-- and inserts into main / external / nbs (created by alembic baseline).",
        "-- =========================================================================",
        "\\set ON_ERROR_STOP on",
        "BEGIN;",
        "",
        "-- Make sure uuid-ossp is available; alembic baseline normally installs it,",
        "-- but a brand-new gimc DB without alembic-up will not have it.",
        "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";",
        "",
    ]


def _guard(stmt: str, stg_qname: str) -> str:
    """Wrap a statement so it is skipped (with NOTICE) if `stg_qname` doesn't exist.

    Lets the ETL stay green on dev VMs / partial-source prod tenants where
    some legacy MySQL tables genuinely don't exist. Verify.py row counts
    catch any *unexpected* skips.
    """
    return (
        "DO $$\nBEGIN\n"
        f"  IF to_regclass({stg_qname!r}) IS NULL THEN\n"
        f"    RAISE NOTICE 'missing source %, skipping', {stg_qname!r};\n"
        "  ELSE\n"
        f"{stmt}"
        "\n  END IF;\nEND$$;\n"
    )


def emit_patient(target_schema: str, src_db: str, stg: str, sources: list[dict]) -> list[str]:
    """Build the schema's `patient` table from one or more source tables."""
    out = [
        f"-- -----------------------------------------------------------------------",
        f"-- {target_schema}.patient  ←  {src_db} ({len(sources)} source table(s))",
        f"-- -----------------------------------------------------------------------",
        f"TRUNCATE TABLE {target_schema}.patient CASCADE;",
        "",
    ]
    for i, src in enumerate(sources):
        src_table = src["source_table"]
        key = src["patient_key"]
        cols = src["columns"]
        filt = src.get("filter")
        distinct = src.get("distinct_on")

        pid = patient_id_expr(target_schema, key)
        target_cols = ["patient_id", "source"] + list(cols.keys())
        select_exprs = [pid, f"'{target_schema}'::patient_source"] + list(cols.values())

        select_clause = ",\n      ".join(select_exprs)
        target_col_list = ", ".join(q_ident(c) if not c.startswith('"') else c
                                    for c in target_cols)

        stg_qname = f"{stg}.{q_ident(src_table)}"
        from_clause = stg_qname
        if distinct:
            from_clause = (
                f"(SELECT DISTINCT ON ({', '.join(q_ident(d) for d in distinct)}) * "
                f"FROM {stg_qname}"
                + (f" WHERE {filt}" if filt else "")
                + f") AS src"
            )
            where_clause = ""
        else:
            where_clause = f"\n    WHERE {filt}" if filt else ""

        update_assigns = ",\n          ".join(
            f"{q_ident(c) if not c.startswith(chr(34)) else c} = "
            f"COALESCE({target_schema}.patient.{q_ident(c) if not c.startswith(chr(34)) else c}, EXCLUDED.{q_ident(c) if not c.startswith(chr(34)) else c})"
            for c in cols.keys()
        )

        stmt = (
            f"    INSERT INTO {target_schema}.patient ({target_col_list})\n"
            f"    SELECT\n"
            f"      {select_clause}\n"
            f"    FROM {from_clause}{where_clause}\n"
            f"    ON CONFLICT (patient_id) DO UPDATE SET\n"
            f"          {update_assigns};"
        )
        out += [
            f"-- source #{i + 1}: {target_schema}.patient ← {src_table}",
            _guard(stmt, stg_qname),
        ]
    return out


def emit_sample(target_schema: str, stg: str, tbl: dict) -> list[str]:
    src_table = tbl["source_table"]
    target_table = tbl["target_table"]
    cols = tbl["columns"]
    sample_id = tbl.get("sample_id")
    filt = tbl.get("filter")
    key = tbl.get("patient_key")
    via_nbs_id = tbl.get("patient_key_via_nbs_id")

    out = [
        f"-- {target_schema}.{target_table}  ←  {stg}.{src_table}",
        f"TRUNCATE TABLE {target_schema}.{q_ident(target_table)} CASCADE;",
        "",
    ]

    # patient_id derivation
    if via_nbs_id:
        # NBS sample tables: join staging to patient via nbs.patient.nbs_id.
        pid_expr = f"p.patient_id"
        join = (
            f"\nJOIN {target_schema}.patient p "
            f"ON p.nbs_id = src.{q_ident(via_nbs_id)}::text"
        )
    elif key:
        pid_expr = patient_id_expr(target_schema, [f"src.{c}" for c in key])
        # rebuild without "src." escaping confusion
        parts = [f"'{target_schema}:'"]
        for i, c in enumerate(key):
            if i:
                parts.append("'|'")
            parts.append(f"COALESCE(src.{q_ident(c)}::text, '')")
        pid_expr = f"uuid_generate_v5({UUID_NS_FN}, {' || '.join(parts)})"
        join = ""
    else:
        raise ValueError(f"{target_schema}.{target_table}: needs patient_key or patient_key_via_nbs_id")

    target_cols = ["patient_id"] + list(cols.keys()) + [
        "ntubiogene_sampleno",
        "v2_source_schema",
    ]
    select_exprs = [pid_expr] + list(cols.values()) + [
        f"src.{q_ident(sample_id)}::text" if sample_id else "NULL::varchar",
        f"'{target_schema}'::varchar",
    ]
    target_col_list = ", ".join(
        c if c.startswith('"') else q_ident(c) for c in target_cols
    )
    select_clause = ",\n    ".join(select_exprs)
    where_clause = f"\nWHERE {filt}" if filt else ""

    # For sample tables that reference patient via nbs_id, we need an EXISTS
    # guard so we don't FK-fail when patient hasn't been seeded.
    if via_nbs_id:
        # JOIN already guards
        pass
    else:
        exists_guard = (
            f"\nAND EXISTS (SELECT 1 FROM {target_schema}.patient _p "
            f"WHERE _p.patient_id = {pid_expr})"
        )
        where_clause += exists_guard

    stg_qname = f"{stg}.{q_ident(src_table)}"
    stmt = (
        f"    INSERT INTO {target_schema}.{q_ident(target_table)} ({target_col_list})\n"
        f"    SELECT\n"
        f"      {select_clause}\n"
        f"    FROM {stg_qname} src{join}{where_clause};"
    )
    out += [_guard(stmt, stg_qname)]
    return out


def emit_footer() -> list[str]:
    return [
        "COMMIT;",
        "",
        "-- transform_2_0.sql complete.",
    ]


def main(argv: list[str]) -> int:
    mapping = yaml.safe_load(MAPPING.read_text())
    out: list[str] = emit_header()

    for target_schema, cfg in mapping["schemas"].items():
        src_db = cfg["source_mysql_db"]
        stg = cfg["staging_schema"]

        out.append(f"-- ========================  schema: {target_schema}  ========================")
        out.append("")
        out += emit_patient(target_schema, src_db, stg, cfg.get("patient_sources", []))

        for tbl in cfg.get("sample_tables", []):
            out += emit_sample(target_schema, stg, tbl)
        out.append("")

    out += emit_footer()
    OUTPUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUTPUT} ({sum(1 for _ in OUTPUT.open())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
