-- =========================================================================
-- transform_2_0.sql — GENERATED by gen_transform_2_0.py. DO NOT EDIT BY HAND.
-- Source: column_mapping_2_0.yaml
--
-- Reads from stg_main / stg_external / stg_nbs (populated by pgloader)
-- and inserts into main / external / nbs (created by alembic baseline).
-- =========================================================================
\set ON_ERROR_STOP on
BEGIN;

-- Make sure uuid-ossp is available; alembic baseline normally installs it,
-- but a brand-new gimc DB without alembic-up will not have it.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ========================  schema: main  ========================

-- -----------------------------------------------------------------------
-- main.patient  ←  2.0 (2 source table(s))
-- -----------------------------------------------------------------------
TRUNCATE TABLE main.patient CASCADE;

-- source #1: main.patient ← 基本資料
DO $$
BEGIN
  IF to_regclass('stg_main."基本資料"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."基本資料"';
  ELSE
    INSERT INTO main.patient ("patient_id", "source", "name", "birthday", "sex", "chartno", "external_chartno", "diagnosis", "diagnosis2", "diagnosis3")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE("chartno"::text, '')),
      'main'::patient_source,
      COALESCE(NULLIF(TRIM(ptname),''), '未命名'),
      COALESCE(birthday, DATE '1900-01-01'),
      (CASE sex WHEN 'M' THEN '男' WHEN 'F' THEN '女' WHEN '男' THEN '男' WHEN '女' THEN '女' ELSE '男' END)::sex,
      chartno,
      chartno_out,
      diagnosis,
      diagnosis2,
      diagnosis3
    FROM stg_main."基本資料"
    WHERE chartno IS NOT NULL AND TRIM(chartno) <> ''
    ON CONFLICT (patient_id) DO UPDATE SET
          "name" = COALESCE(main.patient."name", EXCLUDED."name"),
          "birthday" = COALESCE(main.patient."birthday", EXCLUDED."birthday"),
          "sex" = COALESCE(main.patient."sex", EXCLUDED."sex"),
          "chartno" = COALESCE(main.patient."chartno", EXCLUDED."chartno"),
          "external_chartno" = COALESCE(main.patient."external_chartno", EXCLUDED."external_chartno"),
          "diagnosis" = COALESCE(main.patient."diagnosis", EXCLUDED."diagnosis"),
          "diagnosis2" = COALESCE(main.patient."diagnosis2", EXCLUDED."diagnosis2"),
          "diagnosis3" = COALESCE(main.patient."diagnosis3", EXCLUDED."diagnosis3");
  END IF;
END$$;

-- source #2: main.patient ← opd
DO $$
BEGIN
  IF to_regclass('stg_main."opd"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."opd"';
  ELSE
    INSERT INTO main.patient ("patient_id", "source", "name", "birthday", "sex", "chartno", "diagnosis")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE("病歷號"::text, '')),
      'main'::patient_source,
      COALESCE(NULLIF(TRIM("病人姓名"),''), '未命名'),
      COALESCE("生日", DATE '1900-01-01'),
      (CASE "性別" WHEN 'M' THEN '男' WHEN 'F' THEN '女' WHEN '男' THEN '男' WHEN '女' THEN '女' ELSE '男' END)::sex,
      "病歷號",
      "主診斷名稱"
    FROM (SELECT DISTINCT ON ("病歷號") * FROM stg_main."opd" WHERE "病歷號" IS NOT NULL AND TRIM("病歷號") <> '') AS src
    ON CONFLICT (patient_id) DO UPDATE SET
          "name" = COALESCE(main.patient."name", EXCLUDED."name"),
          "birthday" = COALESCE(main.patient."birthday", EXCLUDED."birthday"),
          "sex" = COALESCE(main.patient."sex", EXCLUDED."sex"),
          "chartno" = COALESCE(main.patient."chartno", EXCLUDED."chartno"),
          "diagnosis" = COALESCE(main.patient."diagnosis", EXCLUDED."diagnosis");
  END IF;
END$$;

-- main.opd  ←  stg_main.opd
TRUNCATE TABLE main."opd" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."opd"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."opd"';
  ELSE
    INSERT INTO main."opd" ("patient_id", "visit_date", "sex", "birthday", "diag_code", "diag_name", "sub_diag1", "sub_diag2", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."病歷號"::text, '')),
    COALESCE("看診日", DATE '1900-01-01'),
    COALESCE(LEFT("性別", 2), '男'),
    COALESCE("生日", DATE '1900-01-01'),
    COALESCE("主診斷碼", ''),
    COALESCE(LEFT("主診斷名稱", 256), ''),
    LEFT("次診斷名稱1", 256),
    LEFT("次診斷名稱2", 256),
    NULL::varchar,
    'main'::varchar
    FROM stg_main."opd" src
WHERE "病歷號" IS NOT NULL AND TRIM("病歷號") <> ''
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."病歷號"::text, '')));
  END IF;
END$$;

-- main.aa  ←  stg_main.aa
TRUNCATE TABLE main."aa" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."aa"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."aa"';
  ELSE
    INSERT INTO main."aa" ("patient_id", "sample_name", "specimen_type", "result", "gln", "citr", "ala", "arg", "leu", "val", "phe", "tyr", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("AA_Sample_name", ''),
    COALESCE("AA-檢體類別", ''),
    COALESCE("AA-Result", ''),
    "AA-Gln",
    "AA-Citr",
    "AA-Ala",
    "AA-Arg",
    "AA-Leu",
    "AA-Val",
    "AA-Phe",
    "AA-Tyr",
    src."AA_Sample_name"::text,
    'main'::varchar
    FROM stg_main."aa" src
WHERE chartno IS NOT NULL AND TRIM(chartno) <> ''
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.aadc  ←  stg_main.aadc
TRUNCATE TABLE main."aadc" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."aadc"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."aadc"';
  ELSE
    INSERT INTO main."aadc" ("patient_id", "sample_name", "conc", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("AADC_Sample_name", ''),
    COALESCE("AADC_Conc", 0),
    src."AADC_Sample_name"::text,
    'main'::varchar
    FROM stg_main."aadc" src
WHERE chartno IS NOT NULL AND "AADC_Conc" IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.ald  ←  stg_main.ald
TRUNCATE TABLE main."ald" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."ald"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."ald"';
  ELSE
    INSERT INTO main."ald" ("patient_id", "sample_name", "conc", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("ALD_Sample_name", ''),
    COALESCE("ALD_Conc", 0),
    src."ALD_Sample_name"::text,
    'main'::varchar
    FROM stg_main."ald" src
WHERE chartno IS NOT NULL AND "ALD_Conc" IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.biomarker  ←  stg_main.biomarker
TRUNCATE TABLE main."biomarker" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."biomarker"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."biomarker"';
  ELSE
    INSERT INTO main."biomarker" ("patient_id", "sample_name", "dbs_lyso_gb3", "dbs_lyso_gl1", "dbs_lyso_sm", "plasma_lyso_gb3", "plasma_lyso_gl1", "plasma_lyso_sm", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("Biomarker_Sample_name", ''),
    "DBS LysoGb3",
    "DBS LysoGL1",
    "DBS Lyso-SM",
    "Plasma LysoGb3",
    "Plasma LysoGL1",
    "Plasma Lyso-SM",
    src."Biomarker_Sample_name"::text,
    'main'::varchar
    FROM stg_main."biomarker" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.dnabank  ←  stg_main.dna bank
TRUNCATE TABLE main."dnabank" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."dna bank"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."dna bank"';
  ELSE
    INSERT INTO main."dnabank" ("patient_id", "orderno", "order", "order_memo", "keyword", "specimenno", "specimen", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("DNA-orderno", ''),
    COALESCE(LEFT("DNA-order", 256), ''),
    LEFT("DNA-order_memo", 256),
    LEFT("DNA-keyword", 256),
    COALESCE("DNA-specimenno", ''),
    COALESCE(LEFT("DNA-specimen", 64), ''),
    src."DNA-orderno"::text,
    'main'::varchar
    FROM stg_main."dna bank" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.enzyme  ←  stg_main.enzyme
TRUNCATE TABLE main."enzyme" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."enzyme"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."enzyme"';
  ELSE
    INSERT INTO main."enzyme" ("patient_id", "sample_name", "specimen_type", "technician", "result", "mps1", "enzyme_mps2", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("Enzyme_Sample_name", ''),
    COALESCE("Enzyme-檢體類別", ''),
    COALESCE("Enzyme-技術人員", ''),
    COALESCE("Enzyme-Result", ''),
    "MPS1",
    "Enzyme-MPS2",
    src."Enzyme_Sample_name"::text,
    'main'::varchar
    FROM stg_main."enzyme" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.gag  ←  stg_main.gag
TRUNCATE TABLE main."gag" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."gag"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."gag"';
  ELSE
    INSERT INTO main."gag" ("patient_id", "sample_name", "specimen_type", "technician", "result", "dmggag", "creatinine", "mggag", "urine_creatinine", "twos", "twos_cre", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("GAG_Sample_name", ''),
    COALESCE("GAG-檢體類別", ''),
    COALESCE("GAG-技術人員", ''),
    COALESCE("GAG-Result", ''),
    "DMBGAG",
    "CREATININE",
    "MGGAG",
    "UrineCreatinine",
    "2S",
    "2SCre",
    src."GAG_Sample_name"::text,
    'main'::varchar
    FROM stg_main."gag" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.lsd  ←  stg_main.lsd
TRUNCATE TABLE main."lsd" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."lsd"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."lsd"';
  ELSE
    INSERT INTO main."lsd" ("patient_id", "sample_name", "gaa", "gla", "abg", "idua", "abg_gaa", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("LSD_Sample_name", ''),
    "GAA",
    "GLA",
    "ABG",
    "IDUA",
    "ABG/GAA",
    src."LSD_Sample_name"::text,
    'main'::varchar
    FROM stg_main."lsd" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.mma  ←  stg_main.mma
TRUNCATE TABLE main."mma" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."mma"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."mma"';
  ELSE
    INSERT INTO main."mma" ("patient_id", "sample_name", "conc", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("MMA_Sample_name", ''),
    COALESCE("MMA_Conc", 0),
    src."MMA_Sample_name"::text,
    'main'::varchar
    FROM stg_main."mma" src
WHERE chartno IS NOT NULL AND "MMA_Conc" IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.mps2  ←  stg_main.mps2
TRUNCATE TABLE main."mps2" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."mps2"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."mps2"';
  ELSE
    INSERT INTO main."mps2" ("patient_id", "sample_name", "mps2", "tpp1", "mps4a", "mps6", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("MPS2_Sample_name", ''),
    "MPS2",
    "TPP1",
    "MPS4A",
    "MPS6",
    src."MPS2_Sample_name"::text,
    'main'::varchar
    FROM stg_main."mps2" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.msms  ←  stg_main.ms/ms
TRUNCATE TABLE main."msms" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."ms/ms"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."ms/ms"';
  ELSE
    INSERT INTO main."msms" ("patient_id", "sample_name", "specimen_type", "result", "ala", "arg", "cit", "gly", "leu", "met", "phe", "tyr", "val", "c0", "c2", "c3", "c5", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("MS/MS_Sample_name", ''),
    COALESCE("MS/MS-檢體類別", ''),
    COALESCE("MS/MS-Result", ''),
    "Ala",
    "Arg",
    "Cit",
    "Gly",
    "Leu/Ile",
    "Met",
    "Phe",
    "Tyr",
    "Val",
    "C0",
    "C02",
    "C03",
    "C05",
    src."MS/MS_Sample_name"::text,
    'main'::varchar
    FROM stg_main."ms/ms" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- main.outbank  ←  stg_main.outbank
TRUNCATE TABLE main."outbank" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_main."outbank"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_main."outbank"';
  ELSE
    INSERT INTO main."outbank" ("patient_id", "sampleno", "shipdate", "assay", "result", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')),
    COALESCE("Outbank_Sampleno", ''),
    COALESCE(shipdate, DATE '1900-01-01'),
    COALESCE(LEFT(assay, 256), ''),
    COALESCE(LEFT("Outbank-result", 512), ''),
    src."Outbank_Sampleno"::text,
    'main'::varchar
    FROM stg_main."outbank" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM main.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'main:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;


-- ========================  schema: external  ========================

-- -----------------------------------------------------------------------
-- external.patient  ←  Out_hospital (2 source table(s))
-- -----------------------------------------------------------------------
TRUNCATE TABLE external.patient CASCADE;

-- source #1: external.patient ← 基本資料
DO $$
BEGIN
  IF to_regclass('stg_external."基本資料"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_external."基本資料"';
  ELSE
    INSERT INTO external.patient ("patient_id", "source", "name", "birthday", "sex", "chartno", "external_chartno", "diagnosis", "diagnosis2", "diagnosis3")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE("chartno"::text, '')),
      'external'::patient_source,
      COALESCE(NULLIF(TRIM(ptname),''), '未命名'),
      COALESCE(birthday, DATE '1900-01-01'),
      (CASE sex WHEN 'M' THEN '男' WHEN 'F' THEN '女' WHEN '男' THEN '男' WHEN '女' THEN '女' ELSE '男' END)::sex,
      chartno,
      chartno_out,
      diagnosis,
      diagnosis2,
      diagnosis3
    FROM stg_external."基本資料"
    WHERE chartno IS NOT NULL AND TRIM(chartno) <> ''
    ON CONFLICT (patient_id) DO UPDATE SET
          "name" = COALESCE(external.patient."name", EXCLUDED."name"),
          "birthday" = COALESCE(external.patient."birthday", EXCLUDED."birthday"),
          "sex" = COALESCE(external.patient."sex", EXCLUDED."sex"),
          "chartno" = COALESCE(external.patient."chartno", EXCLUDED."chartno"),
          "external_chartno" = COALESCE(external.patient."external_chartno", EXCLUDED."external_chartno"),
          "diagnosis" = COALESCE(external.patient."diagnosis", EXCLUDED."diagnosis"),
          "diagnosis2" = COALESCE(external.patient."diagnosis2", EXCLUDED."diagnosis2"),
          "diagnosis3" = COALESCE(external.patient."diagnosis3", EXCLUDED."diagnosis3");
  END IF;
END$$;

-- source #2: external.patient ← opd
DO $$
BEGIN
  IF to_regclass('stg_external."opd"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_external."opd"';
  ELSE
    INSERT INTO external.patient ("patient_id", "source", "name", "birthday", "sex", "chartno", "diagnosis")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE("病歷號"::text, '')),
      'external'::patient_source,
      COALESCE(NULLIF(TRIM("病人姓名"),''), '未命名'),
      COALESCE("生日", DATE '1900-01-01'),
      (CASE "性別" WHEN 'M' THEN '男' WHEN 'F' THEN '女' WHEN '男' THEN '男' WHEN '女' THEN '女' ELSE '男' END)::sex,
      "病歷號",
      "主診斷名稱"
    FROM (SELECT DISTINCT ON ("病歷號") * FROM stg_external."opd" WHERE "病歷號" IS NOT NULL AND TRIM("病歷號") <> '') AS src
    ON CONFLICT (patient_id) DO UPDATE SET
          "name" = COALESCE(external.patient."name", EXCLUDED."name"),
          "birthday" = COALESCE(external.patient."birthday", EXCLUDED."birthday"),
          "sex" = COALESCE(external.patient."sex", EXCLUDED."sex"),
          "chartno" = COALESCE(external.patient."chartno", EXCLUDED."chartno"),
          "diagnosis" = COALESCE(external.patient."diagnosis", EXCLUDED."diagnosis");
  END IF;
END$$;

-- external.opd  ←  stg_external.opd
TRUNCATE TABLE external."opd" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_external."opd"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_external."opd"';
  ELSE
    INSERT INTO external."opd" ("patient_id", "visit_date", "sex", "birthday", "diag_code", "diag_name", "sub_diag1", "sub_diag2", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."病歷號"::text, '')),
    COALESCE("看診日", DATE '1900-01-01'),
    COALESCE(LEFT("性別", 2), '男'),
    COALESCE("生日", DATE '1900-01-01'),
    COALESCE("主診斷碼", ''),
    COALESCE(LEFT("主診斷名稱", 256), ''),
    LEFT("次診斷名稱1", 256),
    LEFT("次診斷名稱2", 256),
    NULL::varchar,
    'external'::varchar
    FROM stg_external."opd" src
WHERE "病歷號" IS NOT NULL
AND EXISTS (SELECT 1 FROM external.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."病歷號"::text, '')));
  END IF;
END$$;

-- external.aa  ←  stg_external.aa
TRUNCATE TABLE external."aa" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_external."aa"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_external."aa"';
  ELSE
    INSERT INTO external."aa" ("patient_id", "sample_name", "specimen_type", "result", "gln", "citr", "ala", "arg", "leu", "val", "phe", "tyr", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')),
    COALESCE("AA_Sample_name", ''),
    COALESCE("AA-檢體類別", ''),
    COALESCE("AA-Result", ''),
    "AA-Gln",
    "AA-Citr",
    "AA-Ala",
    "AA-Arg",
    "AA-Leu",
    "AA-Val",
    "AA-Phe",
    "AA-Tyr",
    src."AA_Sample_name"::text,
    'external'::varchar
    FROM stg_external."aa" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM external.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- external.biomarker  ←  stg_external.biomarker
TRUNCATE TABLE external."biomarker" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_external."biomarker"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_external."biomarker"';
  ELSE
    INSERT INTO external."biomarker" ("patient_id", "sample_name", "dbs_lyso_gb3", "dbs_lyso_gl1", "dbs_lyso_sm", "plasma_lyso_gb3", "plasma_lyso_gl1", "plasma_lyso_sm", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')),
    COALESCE("Biomarker_Sample_name", ''),
    "DBS LysoGb3",
    "DBS LysoGL1",
    "DBS Lyso-SM",
    "Plasma LysoGb3",
    "Plasma LysoGL1",
    "Plasma Lyso-SM",
    src."Biomarker_Sample_name"::text,
    'external'::varchar
    FROM stg_external."biomarker" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM external.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- external.enzyme  ←  stg_external.enzyme
TRUNCATE TABLE external."enzyme" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_external."enzyme"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_external."enzyme"';
  ELSE
    INSERT INTO external."enzyme" ("patient_id", "sample_name", "specimen_type", "technician", "result", "mps1", "enzyme_mps2", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')),
    COALESCE("Enzyme_Sample_name", ''),
    COALESCE("Enzyme-檢體類別", ''),
    COALESCE("Enzyme-技術人員", ''),
    COALESCE("Enzyme-Result", ''),
    "MPS1",
    "Enzyme-MPS2",
    src."Enzyme_Sample_name"::text,
    'external'::varchar
    FROM stg_external."enzyme" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM external.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- external.gag  ←  stg_external.gag
TRUNCATE TABLE external."gag" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_external."gag"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_external."gag"';
  ELSE
    INSERT INTO external."gag" ("patient_id", "sample_name", "specimen_type", "technician", "result", "dmggag", "creatinine", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')),
    COALESCE("GAG_Sample_name", ''),
    COALESCE("GAG-檢體類別", ''),
    COALESCE("GAG-技術人員", ''),
    COALESCE("GAG-Result", ''),
    "DMBGAG",
    "CREATININE",
    src."GAG_Sample_name"::text,
    'external'::varchar
    FROM stg_external."gag" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM external.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- external.lsd  ←  stg_external.lsd
TRUNCATE TABLE external."lsd" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_external."lsd"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_external."lsd"';
  ELSE
    INSERT INTO external."lsd" ("patient_id", "sample_name", "gaa", "gla", "abg", "idua", "abg_gaa", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')),
    COALESCE("LSD_Sample_name", ''),
    "GAA",
    "GLA",
    "ABG",
    "IDUA",
    "ABG/GAA",
    src."LSD_Sample_name"::text,
    'external'::varchar
    FROM stg_external."lsd" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM external.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- external.msms  ←  stg_external.ms/ms
TRUNCATE TABLE external."msms" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_external."ms/ms"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_external."ms/ms"';
  ELSE
    INSERT INTO external."msms" ("patient_id", "sample_name", "specimen_type", "result", "ala", "arg", "cit", "gly", "leu", "met", "phe", "tyr", "val", "c0", "c2", "c3", "c5", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')),
    COALESCE("MS/MS_Sample_name", ''),
    COALESCE("MS/MS-檢體類別", ''),
    COALESCE("MS/MS-Result", ''),
    "Ala",
    "Arg",
    "Cit",
    "Gly",
    "Leu/Ile",
    "Met",
    "Phe",
    "Tyr",
    "Val",
    "C0",
    "C02",
    "C03",
    "C05",
    src."MS/MS_Sample_name"::text,
    'external'::varchar
    FROM stg_external."ms/ms" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM external.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;

-- external.outbank  ←  stg_external.outbank
TRUNCATE TABLE external."outbank" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_external."outbank"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_external."outbank"';
  ELSE
    INSERT INTO external."outbank" ("patient_id", "sampleno", "shipdate", "assay", "result", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')),
    COALESCE("Outbank_Sampleno", ''),
    COALESCE(shipdate, DATE '1900-01-01'),
    COALESCE(LEFT(assay, 256), ''),
    COALESCE(LEFT("Outbank-result", 512), ''),
    src."Outbank_Sampleno"::text,
    'external'::varchar
    FROM stg_external."outbank" src
WHERE chartno IS NOT NULL
AND EXISTS (SELECT 1 FROM external.patient _p WHERE _p.patient_id = uuid_generate_v5(uuid_ns_oid(), 'external:' || COALESCE(src."chartno"::text, '')));
  END IF;
END$$;


-- ========================  schema: nbs  ========================

-- -----------------------------------------------------------------------
-- nbs.patient  ←  new_born_screen (3 source table(s))
-- -----------------------------------------------------------------------
TRUNCATE TABLE nbs.patient CASCADE;

-- source #1: nbs.patient ← nbs
DO $$
BEGIN
  IF to_regclass('stg_nbs."nbs"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_nbs."nbs"';
  ELSE
    INSERT INTO nbs.patient ("patient_id", "source", "name", "birthday", "sex", "chartno", "nbs_id", "category")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'nbs:' || COALESCE("Screen_id"::text, '')),
      'nbs'::patient_source,
      COALESCE(NULLIF(TRIM("母姓名"),''), '未命名'),
      COALESCE("個案生日", DATE '1900-01-01'),
      (CASE "個案性別" WHEN 'M' THEN '男' WHEN 'F' THEN '女' WHEN '1' THEN '男' WHEN '2' THEN '女' WHEN '男' THEN '男' WHEN '女' THEN '女' ELSE '男' END)::sex,
      "個案病歷號",
      "Screen_id",
      'inhouse'
    FROM stg_nbs."nbs"
    WHERE "Screen_id" IS NOT NULL AND TRIM("Screen_id") <> ''
    ON CONFLICT (patient_id) DO UPDATE SET
          "name" = COALESCE(nbs.patient."name", EXCLUDED."name"),
          "birthday" = COALESCE(nbs.patient."birthday", EXCLUDED."birthday"),
          "sex" = COALESCE(nbs.patient."sex", EXCLUDED."sex"),
          "chartno" = COALESCE(nbs.patient."chartno", EXCLUDED."chartno"),
          "nbs_id" = COALESCE(nbs.patient."nbs_id", EXCLUDED."nbs_id"),
          "category" = COALESCE(nbs.patient."category", EXCLUDED."category");
  END IF;
END$$;

-- source #2: nbs.patient ← 系統外自費
DO $$
BEGIN
  IF to_regclass('stg_nbs."系統外自費"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_nbs."系統外自費"';
  ELSE
    INSERT INTO nbs.patient ("patient_id", "source", "name", "birthday", "sex", "chartno", "nbs_id", "category")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'nbs:' || COALESCE("Screen_id"::text, '')),
      'nbs'::patient_source,
      COALESCE(NULLIF(TRIM("Mother_name"),''), '未命名'),
      COALESCE("生日", DATE '1900-01-01'),
      (CASE "Sex" WHEN 'M' THEN '男' WHEN 'F' THEN '女' WHEN '1' THEN '男' WHEN '2' THEN '女' WHEN '男' THEN '男' WHEN '女' THEN '女' ELSE '男' END)::sex,
      "CHARTNO",
      "Screen_id",
      'sys_external_self_pay'
    FROM (SELECT DISTINCT ON ("Screen_id") * FROM stg_nbs."系統外自費" WHERE "Screen_id" IS NOT NULL) AS src
    ON CONFLICT (patient_id) DO UPDATE SET
          "name" = COALESCE(nbs.patient."name", EXCLUDED."name"),
          "birthday" = COALESCE(nbs.patient."birthday", EXCLUDED."birthday"),
          "sex" = COALESCE(nbs.patient."sex", EXCLUDED."sex"),
          "chartno" = COALESCE(nbs.patient."chartno", EXCLUDED."chartno"),
          "nbs_id" = COALESCE(nbs.patient."nbs_id", EXCLUDED."nbs_id"),
          "category" = COALESCE(nbs.patient."category", EXCLUDED."category");
  END IF;
END$$;

-- source #3: nbs.patient ← 門診個案
DO $$
BEGIN
  IF to_regclass('stg_nbs."門診個案"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_nbs."門診個案"';
  ELSE
    INSERT INTO nbs.patient ("patient_id", "source", "name", "birthday", "sex", "chartno", "nbs_id", "category")
    SELECT
      uuid_generate_v5(uuid_ns_oid(), 'nbs:' || COALESCE("Screen_id"::text, '')),
      'nbs'::patient_source,
      COALESCE(NULLIF(TRIM("OPD_母姓名"),''), '未命名'),
      COALESCE("出生日期", DATE '1900-01-01'),
      (CASE "嬰兒性別" WHEN 'M' THEN '男' WHEN 'F' THEN '女' WHEN '1' THEN '男' WHEN '2' THEN '女' WHEN '男' THEN '男' WHEN '女' THEN '女' ELSE '男' END)::sex,
      "病歷號",
      "Screen_id",
      'opd'
    FROM (SELECT DISTINCT ON ("Screen_id") * FROM stg_nbs."門診個案" WHERE "Screen_id" IS NOT NULL) AS src
    ON CONFLICT (patient_id) DO UPDATE SET
          "name" = COALESCE(nbs.patient."name", EXCLUDED."name"),
          "birthday" = COALESCE(nbs.patient."birthday", EXCLUDED."birthday"),
          "sex" = COALESCE(nbs.patient."sex", EXCLUDED."sex"),
          "chartno" = COALESCE(nbs.patient."chartno", EXCLUDED."chartno"),
          "nbs_id" = COALESCE(nbs.patient."nbs_id", EXCLUDED."nbs_id"),
          "category" = COALESCE(nbs.patient."category", EXCLUDED."category");
  END IF;
END$$;

-- nbs.msms  ←  stg_nbs.ms
TRUNCATE TABLE nbs."msms" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_nbs."ms"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_nbs."ms"';
  ELSE
    INSERT INTO nbs."msms" ("patient_id", "sample_name", "specimen_type", "result", "ala", "arg", "cit", "gly", "leu", "met", "phe", "tyr", "val", "c0", "c2", "c3", "c5", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      p.patient_id,
    COALESCE("Sample_name", ''),
    '',
    '',
    "Ala",
    "Arg",
    "Cit",
    "Gly",
    "Leu/Ile",
    "Met",
    "Phe",
    "Tyr",
    "Val",
    "C0",
    "C02",
    "C03",
    "C05",
    src."Sample_name"::text,
    'nbs'::varchar
    FROM stg_nbs."ms" src
JOIN nbs.patient p ON p.nbs_id = src."Sample_name"::text
WHERE "Sample_name" IS NOT NULL;
  END IF;
END$$;

-- nbs.bd  ←  stg_nbs.bd
TRUNCATE TABLE nbs."bd" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_nbs."bd"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_nbs."bd"';
  ELSE
    INSERT INTO nbs."bd" ("patient_id", "sample_id", "collect_date", "result", "biotinidase_activity", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      p.patient_id,
    COALESCE("Sample_name", ''),
    DATE '1900-01-01',
    '',
    "BTD Conc",
    src."Sample_name"::text,
    'nbs'::varchar
    FROM stg_nbs."bd" src
JOIN nbs.patient p ON p.nbs_id = src."Sample_name"::text
WHERE "Sample_name" IS NOT NULL AND "BTD Conc" IS NOT NULL;
  END IF;
END$$;

-- nbs.cah  ←  stg_nbs.cah
TRUNCATE TABLE nbs."cah" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_nbs."cah"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_nbs."cah"';
  ELSE
    INSERT INTO nbs."cah" ("patient_id", "cah_id", "sample_id", "collect_date", "result", "ohp17", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      p.patient_id,
    COALESCE("Sample_name", ''),
    COALESCE("Sample_name", ''),
    DATE '1900-01-01',
    '',
    "N17OHP Conc",
    src."Sample_name"::text,
    'nbs'::varchar
    FROM stg_nbs."cah" src
JOIN nbs.patient p ON p.nbs_id = src."Sample_name"::text
WHERE "Sample_name" IS NOT NULL AND "N17OHP Conc" IS NOT NULL;
  END IF;
END$$;

-- nbs.dmd  ←  stg_nbs.dmd
TRUNCATE TABLE nbs."dmd" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_nbs."dmd"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_nbs."dmd"';
  ELSE
    INSERT INTO nbs."dmd" ("patient_id", "dmd_id", "sample_id", "collect_date", "result", "ck", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      p.patient_id,
    COALESCE("Sample_name", ''),
    COALESCE("Sample_name", ''),
    DATE '1900-01-01',
    '',
    "CKMM Conc",
    src."Sample_name"::text,
    'nbs'::varchar
    FROM stg_nbs."dmd" src
JOIN nbs.patient p ON p.nbs_id = src."Sample_name"::text
WHERE "Sample_name" IS NOT NULL AND "CKMM Conc" IS NOT NULL;
  END IF;
END$$;

-- nbs.g6pd  ←  stg_nbs.g6pd
TRUNCATE TABLE nbs."g6pd" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_nbs."g6pd"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_nbs."g6pd"';
  ELSE
    INSERT INTO nbs."g6pd" ("patient_id", "sample_id", "collect_date", "result", "g6pd_activity", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      p.patient_id,
    COALESCE("Sample_name", ''),
    DATE '1900-01-01',
    '',
    "G6PD Conc",
    src."Sample_name"::text,
    'nbs'::varchar
    FROM stg_nbs."g6pd" src
JOIN nbs.patient p ON p.nbs_id = src."Sample_name"::text
WHERE "Sample_name" IS NOT NULL AND "G6PD Conc" IS NOT NULL;
  END IF;
END$$;

-- nbs.sma_scid  ←  stg_nbs.sma_scid
TRUNCATE TABLE nbs."sma_scid" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_nbs."sma_scid"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_nbs."sma_scid"';
  ELSE
    INSERT INTO nbs."sma_scid" ("patient_id", "sample_id", "collect_date", "result", "smn1_copies", "trec", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      p.patient_id,
    COALESCE("Sample_name", ''),
    DATE '1900-01-01',
    '',
    CAST("SMN1 CT" AS INTEGER),
    "TREC Quantity",
    src."Sample_name"::text,
    'nbs'::varchar
    FROM stg_nbs."sma_scid" src
JOIN nbs.patient p ON p.nbs_id = src."Sample_name"::text
WHERE "Sample_name" IS NOT NULL;
  END IF;
END$$;

-- nbs.biomarker  ←  stg_nbs.biomarker
TRUNCATE TABLE nbs."biomarker" CASCADE;

DO $$
BEGIN
  IF to_regclass('stg_nbs."biomarker"') IS NULL THEN
    RAISE NOTICE 'missing source %, skipping', 'stg_nbs."biomarker"';
  ELSE
    INSERT INTO nbs."biomarker" ("patient_id", "sample_name", "ntubiogene_sampleno", "v2_source_schema")
    SELECT
      p.patient_id,
    COALESCE("Sample_name", ''),
    src."Sample_name"::text,
    'nbs'::varchar
    FROM stg_nbs."biomarker" src
JOIN nbs.patient p ON p.nbs_id = src."Sample_name"::text
WHERE FALSE;
  END IF;
END$$;


COMMIT;

-- transform_2_0.sql complete.
