"""disease_modules

Revision ID: f7a185a32e9a
Revises: 2dfd5ee99ec5
Create Date: 2026-04-30 05:46:44.707378
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from shared.models._ddl import (
    drop_trigger_set_updated_at_sql,
    trigger_set_updated_at_sql,
)

# Disease tables added in this revision; each gets a BEFORE UPDATE trigger.
_NEW_TABLES: list[tuple[str, str]] = [
    ("main", "aadc"),
    ("main", "ald"),
    ("main", "mma"),
    ("main", "mps2"),
    ("main", "lsd"),
    ("main", "gag"),
    ("external", "lsd"),
    ("external", "gag"),
]

# revision identifiers, used by Alembic.
revision: str = 'f7a185a32e9a'
down_revision: Union[str, Sequence[str], None] = '2dfd5ee99ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gag',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=False),
    sa.Column('technician', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('dmggag', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('creatinine', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['external.patient.patient_id'], name=op.f('fk_gag_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gag')),
    schema='external'
    )
    op.create_index(op.f('ix_gag_patient_id'), 'gag', ['patient_id'], unique=False, schema='external')
    op.create_table('lsd',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('gaa', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gla', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('abg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('idua', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('abg_gaa', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['external.patient.patient_id'], name=op.f('fk_lsd_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lsd')),
    schema='external'
    )
    op.create_index(op.f('ix_lsd_patient_id'), 'lsd', ['patient_id'], unique=False, schema='external')
    op.create_table('aadc',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('conc', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_aadc_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aadc')),
    schema='main'
    )
    op.create_index(op.f('ix_aadc_patient_id'), 'aadc', ['patient_id'], unique=False, schema='main')
    op.create_table('ald',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('conc', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_ald_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ald')),
    schema='main'
    )
    op.create_index(op.f('ix_ald_patient_id'), 'ald', ['patient_id'], unique=False, schema='main')
    op.create_table('gag',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=False),
    sa.Column('technician', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('dmggag', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('creatinine', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_gag_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gag')),
    schema='main'
    )
    op.create_index(op.f('ix_gag_patient_id'), 'gag', ['patient_id'], unique=False, schema='main')
    op.create_table('lsd',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('gaa', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gla', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('abg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('idua', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('abg_gaa', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_lsd_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lsd')),
    schema='main'
    )
    op.create_index(op.f('ix_lsd_patient_id'), 'lsd', ['patient_id'], unique=False, schema='main')
    op.create_table('mma',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('conc', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_mma_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mma')),
    schema='main'
    )
    op.create_index(op.f('ix_mma_patient_id'), 'mma', ['patient_id'], unique=False, schema='main')
    op.create_table('mps2',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('mps2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tpp1', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('mps4a', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('mps6', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_mps2_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mps2')),
    schema='main'
    )
    op.create_index(op.f('ix_mps2_patient_id'), 'mps2', ['patient_id'], unique=False, schema='main')
    # ### end Alembic commands ###

    for schema_name, table_name in _NEW_TABLES:
        op.execute(trigger_set_updated_at_sql(schema_name, table_name))


def downgrade() -> None:
    for schema_name, table_name in reversed(_NEW_TABLES):
        op.execute(drop_trigger_set_updated_at_sql(schema_name, table_name))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mps2_patient_id'), table_name='mps2', schema='main')
    op.drop_table('mps2', schema='main')
    op.drop_index(op.f('ix_mma_patient_id'), table_name='mma', schema='main')
    op.drop_table('mma', schema='main')
    op.drop_index(op.f('ix_lsd_patient_id'), table_name='lsd', schema='main')
    op.drop_table('lsd', schema='main')
    op.drop_index(op.f('ix_gag_patient_id'), table_name='gag', schema='main')
    op.drop_table('gag', schema='main')
    op.drop_index(op.f('ix_ald_patient_id'), table_name='ald', schema='main')
    op.drop_table('ald', schema='main')
    op.drop_index(op.f('ix_aadc_patient_id'), table_name='aadc', schema='main')
    op.drop_table('aadc', schema='main')
    op.drop_index(op.f('ix_lsd_patient_id'), table_name='lsd', schema='external')
    op.drop_table('lsd', schema='external')
    op.drop_index(op.f('ix_gag_patient_id'), table_name='gag', schema='external')
    op.drop_table('gag', schema='external')
    # ### end Alembic commands ###
