"""baseline_mvp1

Revision ID: 2dfd5ee99ec5
Revises: 
Create Date: 2026-04-30 05:39:08.126450
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from shared.models._ddl import (
    CREATE_ENUM_TYPES,
    DROP_ENUM_TYPES,
    DROP_SET_UPDATED_AT_FUNCTION,
    SET_UPDATED_AT_FUNCTION,
    drop_trigger_set_updated_at_sql,
    trigger_set_updated_at_sql,
)

# Tables that have BOTH created_at and updated_at — get a BEFORE UPDATE
# trigger calling public.set_updated_at(). links.patient_link only has
# created_at (immutable junction rows) so it is excluded.
_TABLES_WITH_UPDATED_AT: list[tuple[str, str]] = [
    ("main", "patient"),
    ("main", "aa"),
    ("main", "msms"),
    ("main", "biomarker"),
    ("main", "opd"),
    ("main", "dnabank"),
    ("main", "outbank"),
    ("main", "enzyme"),
    ("external", "patient"),
    ("external", "aa"),
    ("external", "msms"),
    ("external", "biomarker"),
    ("external", "opd"),
    ("external", "outbank"),
    ("external", "enzyme"),
    ("nbs", "patient"),
    ("nbs", "aa"),
    ("nbs", "msms"),
    ("nbs", "biomarker"),
    ("nbs", "opd"),
    ("nbs", "outbank"),
    ("nbs", "bd"),
    ("nbs", "cah"),
    ("nbs", "cah_tgal"),
    ("nbs", "dmd"),
    ("nbs", "dmd_tsh"),
    ("nbs", "g6pd"),
    ("nbs", "sma_scid"),
]

# revision identifiers, used by Alembic.
revision: str = '2dfd5ee99ec5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Schemas — IF NOT EXISTS so the migration is safe on a DB that was
    #    bootstrapped via setup-postgres.sh (which already created them).
    for schema_name in ("main", "external", "nbs", "links", "ref"):
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema_name}";')

    # 2. ENUM types — created in `public` so they're visible to every schema.
    #    All ENUM columns below pass `create_type=False` so SQLAlchemy
    #    doesn't try to create them again per-table.
    for stmt in CREATE_ENUM_TYPES:
        op.execute(stmt)

    # 3. Shared trigger function — set NEW.updated_at = now() on UPDATE.
    op.execute(SET_UPDATED_AT_FUNCTION)

    # 4. Tables (autogenerated; `create_type=False` injected on every ENUM
    #    column so the type lookup goes to the ones we just created).
    op.create_table('patient',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('source', postgresql.ENUM('main', 'external', 'nbs', name='patient_source', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('sex', postgresql.ENUM('男', '女', name='sex', create_type=False), nullable=False),
    sa.Column('chartno', sa.String(length=32), nullable=True),
    sa.Column('external_chartno', sa.String(length=32), nullable=True),
    sa.Column('nbs_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('diagnosis', sa.String(length=256), nullable=True),
    sa.Column('diagnosis2', sa.String(length=256), nullable=True),
    sa.Column('diagnosis3', sa.String(length=256), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('pk_patient')),
    schema='external'
    )
    op.create_index('ix_patient_birthday', 'patient', ['birthday'], unique=False, schema='external')
    op.create_index('ix_patient_name', 'patient', ['name'], unique=False, schema='external')
    op.create_table('patient_link',
    sa.Column('patient_id_a', sa.UUID(), nullable=False),
    sa.Column('patient_id_b', sa.UUID(), nullable=False),
    sa.Column('link_kind', postgresql.ENUM('same_person', 'probable', 'manual', name='link_kind', create_type=False), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('patient_id_a < patient_id_b', name=op.f('ck_patient_link_patient_link_canonical_pair')),
    sa.PrimaryKeyConstraint('patient_id_a', 'patient_id_b', name='pk_patient_link'),
    schema='links'
    )
    op.create_index('ix_link_b', 'patient_link', ['patient_id_b'], unique=False, schema='links')
    op.create_table('patient',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('source', postgresql.ENUM('main', 'external', 'nbs', name='patient_source', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('sex', postgresql.ENUM('男', '女', name='sex', create_type=False), nullable=False),
    sa.Column('chartno', sa.String(length=32), nullable=True),
    sa.Column('external_chartno', sa.String(length=32), nullable=True),
    sa.Column('nbs_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('diagnosis', sa.String(length=256), nullable=True),
    sa.Column('diagnosis2', sa.String(length=256), nullable=True),
    sa.Column('diagnosis3', sa.String(length=256), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('pk_patient')),
    schema='main'
    )
    op.create_index('ix_patient_birthday', 'patient', ['birthday'], unique=False, schema='main')
    op.create_index('ix_patient_name', 'patient', ['name'], unique=False, schema='main')
    op.create_table('patient',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('source', postgresql.ENUM('main', 'external', 'nbs', name='patient_source', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('sex', postgresql.ENUM('男', '女', name='sex', create_type=False), nullable=False),
    sa.Column('chartno', sa.String(length=32), nullable=True),
    sa.Column('external_chartno', sa.String(length=32), nullable=True),
    sa.Column('nbs_id', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('diagnosis', sa.String(length=256), nullable=True),
    sa.Column('diagnosis2', sa.String(length=256), nullable=True),
    sa.Column('diagnosis3', sa.String(length=256), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id', name=op.f('pk_patient')),
    schema='nbs'
    )
    op.create_index('ix_patient_birthday', 'patient', ['birthday'], unique=False, schema='nbs')
    op.create_index('ix_patient_name', 'patient', ['name'], unique=False, schema='nbs')
    op.create_table('aa',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('gln', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('citr', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ala', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('arg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('leu', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('val', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('phe', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tyr', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['external.patient.patient_id'], name=op.f('fk_aa_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aa')),
    schema='external'
    )
    op.create_index('ix_aa_leu_notnull', 'aa', ['leu'], unique=False, schema='external', postgresql_where=sa.text('leu IS NOT NULL'))
    op.create_index(op.f('ix_aa_patient_id'), 'aa', ['patient_id'], unique=False, schema='external')
    op.create_table('biomarker',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('dbs_lyso_gb3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dbs_lyso_gl1', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dbs_lyso_sm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('plasma_lyso_gb3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('plasma_lyso_gl1', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('plasma_lyso_sm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['external.patient.patient_id'], name=op.f('fk_biomarker_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biomarker')),
    schema='external'
    )
    op.create_index('ix_biomarker_lyso_high', 'biomarker', ['dbs_lyso_gb3'], unique=False, schema='external', postgresql_where=sa.text('dbs_lyso_gb3 > 5'))
    op.create_index(op.f('ix_biomarker_patient_id'), 'biomarker', ['patient_id'], unique=False, schema='external')
    op.create_table('enzyme',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=False),
    sa.Column('technician', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('mps1', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('enzyme_mps2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['external.patient.patient_id'], name=op.f('fk_enzyme_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enzyme')),
    schema='external'
    )
    op.create_index(op.f('ix_enzyme_patient_id'), 'enzyme', ['patient_id'], unique=False, schema='external')
    op.create_table('msms',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('ala', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('arg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cit', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gly', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('leu', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('met', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('phe', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tyr', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('val', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c0', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c5', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['external.patient.patient_id'], name=op.f('fk_msms_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_msms')),
    schema='external'
    )
    op.create_index(op.f('ix_msms_patient_id'), 'msms', ['patient_id'], unique=False, schema='external')
    op.create_table('opd',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=2), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('diag_code', sa.String(length=32), nullable=False),
    sa.Column('diag_name', sa.String(length=256), nullable=False),
    sa.Column('sub_diag1', sa.String(length=256), nullable=True),
    sa.Column('sub_diag2', sa.String(length=256), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['external.patient.patient_id'], name=op.f('fk_opd_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opd')),
    schema='external'
    )
    op.create_index(op.f('ix_opd_patient_id'), 'opd', ['patient_id'], unique=False, schema='external')
    op.create_table('outbank',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sampleno', sa.String(length=64), nullable=False),
    sa.Column('shipdate', sa.Date(), nullable=False),
    sa.Column('assay', sa.String(length=256), nullable=False),
    sa.Column('result', sa.String(length=512), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['external.patient.patient_id'], name=op.f('fk_outbank_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbank')),
    schema='external'
    )
    op.create_index(op.f('ix_outbank_patient_id'), 'outbank', ['patient_id'], unique=False, schema='external')
    op.create_table('aa',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('gln', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('citr', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ala', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('arg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('leu', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('val', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('phe', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tyr', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_aa_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aa')),
    schema='main'
    )
    op.create_index('ix_aa_leu_notnull', 'aa', ['leu'], unique=False, schema='main', postgresql_where=sa.text('leu IS NOT NULL'))
    op.create_index(op.f('ix_aa_patient_id'), 'aa', ['patient_id'], unique=False, schema='main')
    op.create_table('biomarker',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('dbs_lyso_gb3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dbs_lyso_gl1', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dbs_lyso_sm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('plasma_lyso_gb3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('plasma_lyso_gl1', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('plasma_lyso_sm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_biomarker_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biomarker')),
    schema='main'
    )
    op.create_index('ix_biomarker_lyso_high', 'biomarker', ['dbs_lyso_gb3'], unique=False, schema='main', postgresql_where=sa.text('dbs_lyso_gb3 > 5'))
    op.create_index(op.f('ix_biomarker_patient_id'), 'biomarker', ['patient_id'], unique=False, schema='main')
    op.create_table('dnabank',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('orderno', sa.String(length=64), nullable=False),
    sa.Column('order', sa.String(length=256), nullable=False),
    sa.Column('order_memo', sa.String(length=256), nullable=True),
    sa.Column('keyword', sa.String(length=256), nullable=True),
    sa.Column('specimenno', sa.String(length=64), nullable=False),
    sa.Column('specimen', sa.String(length=64), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_dnabank_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dnabank')),
    schema='main'
    )
    op.create_index(op.f('ix_dnabank_patient_id'), 'dnabank', ['patient_id'], unique=False, schema='main')
    op.create_table('enzyme',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=False),
    sa.Column('technician', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('mps1', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('enzyme_mps2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_enzyme_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enzyme')),
    schema='main'
    )
    op.create_index(op.f('ix_enzyme_patient_id'), 'enzyme', ['patient_id'], unique=False, schema='main')
    op.create_table('msms',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('ala', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('arg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cit', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gly', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('leu', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('met', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('phe', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tyr', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('val', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c0', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c5', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_msms_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_msms')),
    schema='main'
    )
    op.create_index(op.f('ix_msms_patient_id'), 'msms', ['patient_id'], unique=False, schema='main')
    op.create_table('opd',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=2), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('diag_code', sa.String(length=32), nullable=False),
    sa.Column('diag_name', sa.String(length=256), nullable=False),
    sa.Column('sub_diag1', sa.String(length=256), nullable=True),
    sa.Column('sub_diag2', sa.String(length=256), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_opd_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opd')),
    schema='main'
    )
    op.create_index(op.f('ix_opd_patient_id'), 'opd', ['patient_id'], unique=False, schema='main')
    op.create_table('outbank',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sampleno', sa.String(length=64), nullable=False),
    sa.Column('shipdate', sa.Date(), nullable=False),
    sa.Column('assay', sa.String(length=256), nullable=False),
    sa.Column('result', sa.String(length=512), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_outbank_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbank')),
    schema='main'
    )
    op.create_index(op.f('ix_outbank_patient_id'), 'outbank', ['patient_id'], unique=False, schema='main')
    op.create_table('aa',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('gln', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('citr', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('ala', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('arg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('leu', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('val', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('phe', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tyr', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['nbs.patient.patient_id'], name=op.f('fk_aa_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aa')),
    schema='nbs'
    )
    op.create_index('ix_aa_leu_notnull', 'aa', ['leu'], unique=False, schema='nbs', postgresql_where=sa.text('leu IS NOT NULL'))
    op.create_index(op.f('ix_aa_patient_id'), 'aa', ['patient_id'], unique=False, schema='nbs')
    op.create_table('bd',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('collect_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('biotinidase_activity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['nbs.patient.patient_id'], name=op.f('fk_bd_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bd')),
    schema='nbs'
    )
    op.create_index(op.f('ix_bd_patient_id'), 'bd', ['patient_id'], unique=False, schema='nbs')
    op.create_table('biomarker',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('dbs_lyso_gb3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dbs_lyso_gl1', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dbs_lyso_sm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('plasma_lyso_gb3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('plasma_lyso_gl1', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('plasma_lyso_sm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['nbs.patient.patient_id'], name=op.f('fk_biomarker_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_biomarker')),
    schema='nbs'
    )
    op.create_index('ix_biomarker_lyso_high', 'biomarker', ['dbs_lyso_gb3'], unique=False, schema='nbs', postgresql_where=sa.text('dbs_lyso_gb3 > 5'))
    op.create_index(op.f('ix_biomarker_patient_id'), 'biomarker', ['patient_id'], unique=False, schema='nbs')
    op.create_table('cah',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('cah_id', sa.String(length=64), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('collect_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('ohp17', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['nbs.patient.patient_id'], name=op.f('fk_cah_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cah')),
    sa.UniqueConstraint('cah_id', name='uq_cah_cah_id'),
    schema='nbs'
    )
    op.create_index('ix_cah_ohp17_notnull', 'cah', ['ohp17'], unique=False, schema='nbs', postgresql_where=sa.text('ohp17 IS NOT NULL'))
    op.create_index(op.f('ix_cah_patient_id'), 'cah', ['patient_id'], unique=False, schema='nbs')
    op.create_table('dmd',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('dmd_id', sa.String(length=64), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('collect_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('ck', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['nbs.patient.patient_id'], name=op.f('fk_dmd_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dmd')),
    sa.UniqueConstraint('dmd_id', name='uq_dmd_dmd_id'),
    schema='nbs'
    )
    op.create_index(op.f('ix_dmd_patient_id'), 'dmd', ['patient_id'], unique=False, schema='nbs')
    op.create_table('g6pd',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('collect_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('g6pd_activity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['nbs.patient.patient_id'], name=op.f('fk_g6pd_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_g6pd')),
    schema='nbs'
    )
    op.create_index(op.f('ix_g6pd_patient_id'), 'g6pd', ['patient_id'], unique=False, schema='nbs')
    op.create_table('msms',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('ala', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('arg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cit', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('gly', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('leu', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('met', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('phe', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tyr', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('val', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c0', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c2', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('c5', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['nbs.patient.patient_id'], name=op.f('fk_msms_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_msms')),
    schema='nbs'
    )
    op.create_index(op.f('ix_msms_patient_id'), 'msms', ['patient_id'], unique=False, schema='nbs')
    op.create_table('opd',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=2), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('diag_code', sa.String(length=32), nullable=False),
    sa.Column('diag_name', sa.String(length=256), nullable=False),
    sa.Column('sub_diag1', sa.String(length=256), nullable=True),
    sa.Column('sub_diag2', sa.String(length=256), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['nbs.patient.patient_id'], name=op.f('fk_opd_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opd')),
    schema='nbs'
    )
    op.create_index(op.f('ix_opd_patient_id'), 'opd', ['patient_id'], unique=False, schema='nbs')
    op.create_table('outbank',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sampleno', sa.String(length=64), nullable=False),
    sa.Column('shipdate', sa.Date(), nullable=False),
    sa.Column('assay', sa.String(length=256), nullable=False),
    sa.Column('result', sa.String(length=512), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['nbs.patient.patient_id'], name=op.f('fk_outbank_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbank')),
    schema='nbs'
    )
    op.create_index(op.f('ix_outbank_patient_id'), 'outbank', ['patient_id'], unique=False, schema='nbs')
    op.create_table('sma_scid',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('collect_date', sa.Date(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('smn1_copies', sa.Integer(), nullable=True),
    sa.Column('trec', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['nbs.patient.patient_id'], name=op.f('fk_sma_scid_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sma_scid')),
    schema='nbs'
    )
    op.create_index(op.f('ix_sma_scid_patient_id'), 'sma_scid', ['patient_id'], unique=False, schema='nbs')
    op.create_table('cah_tgal',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('cah_id', sa.String(length=64), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('collect_date', sa.Date(), nullable=False),
    sa.Column('total_galactose', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cah_id'], ['nbs.cah.cah_id'], name=op.f('fk_cah_tgal_cah_id_cah'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cah_tgal')),
    schema='nbs'
    )
    op.create_index(op.f('ix_cah_tgal_cah_id'), 'cah_tgal', ['cah_id'], unique=False, schema='nbs')
    op.create_table('dmd_tsh',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('dmd_id', sa.String(length=64), nullable=False),
    sa.Column('sample_id', sa.String(length=64), nullable=False),
    sa.Column('collect_date', sa.Date(), nullable=False),
    sa.Column('tsh', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['dmd_id'], ['nbs.dmd.dmd_id'], name=op.f('fk_dmd_tsh_dmd_id_dmd'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dmd_tsh')),
    schema='nbs'
    )
    op.create_index(op.f('ix_dmd_tsh_dmd_id'), 'dmd_tsh', ['dmd_id'], unique=False, schema='nbs')
    op.create_index('ix_dmd_tsh_tsh_notnull', 'dmd_tsh', ['tsh'], unique=False, schema='nbs', postgresql_where=sa.text('tsh IS NOT NULL'))
    # ### end Alembic commands ###

    # 5. BEFORE UPDATE triggers — auto-refresh updated_at for every table
    #    that has both created_at and updated_at columns.
    for schema_name, table_name in _TABLES_WITH_UPDATED_AT:
        op.execute(trigger_set_updated_at_sql(schema_name, table_name))


def downgrade() -> None:
    # 1. Drop triggers (no-op if upgrade dropped tables — the trigger goes
    #    with its table — but explicit drop covers the partial-failure case).
    for schema_name, table_name in reversed(_TABLES_WITH_UPDATED_AT):
        op.execute(drop_trigger_set_updated_at_sql(schema_name, table_name))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dmd_tsh_tsh_notnull', table_name='dmd_tsh', schema='nbs', postgresql_where=sa.text('tsh IS NOT NULL'))
    op.drop_index(op.f('ix_dmd_tsh_dmd_id'), table_name='dmd_tsh', schema='nbs')
    op.drop_table('dmd_tsh', schema='nbs')
    op.drop_index(op.f('ix_cah_tgal_cah_id'), table_name='cah_tgal', schema='nbs')
    op.drop_table('cah_tgal', schema='nbs')
    op.drop_index(op.f('ix_sma_scid_patient_id'), table_name='sma_scid', schema='nbs')
    op.drop_table('sma_scid', schema='nbs')
    op.drop_index(op.f('ix_outbank_patient_id'), table_name='outbank', schema='nbs')
    op.drop_table('outbank', schema='nbs')
    op.drop_index(op.f('ix_opd_patient_id'), table_name='opd', schema='nbs')
    op.drop_table('opd', schema='nbs')
    op.drop_index(op.f('ix_msms_patient_id'), table_name='msms', schema='nbs')
    op.drop_table('msms', schema='nbs')
    op.drop_index(op.f('ix_g6pd_patient_id'), table_name='g6pd', schema='nbs')
    op.drop_table('g6pd', schema='nbs')
    op.drop_index(op.f('ix_dmd_patient_id'), table_name='dmd', schema='nbs')
    op.drop_table('dmd', schema='nbs')
    op.drop_index(op.f('ix_cah_patient_id'), table_name='cah', schema='nbs')
    op.drop_index('ix_cah_ohp17_notnull', table_name='cah', schema='nbs', postgresql_where=sa.text('ohp17 IS NOT NULL'))
    op.drop_table('cah', schema='nbs')
    op.drop_index(op.f('ix_biomarker_patient_id'), table_name='biomarker', schema='nbs')
    op.drop_index('ix_biomarker_lyso_high', table_name='biomarker', schema='nbs', postgresql_where=sa.text('dbs_lyso_gb3 > 5'))
    op.drop_table('biomarker', schema='nbs')
    op.drop_index(op.f('ix_bd_patient_id'), table_name='bd', schema='nbs')
    op.drop_table('bd', schema='nbs')
    op.drop_index(op.f('ix_aa_patient_id'), table_name='aa', schema='nbs')
    op.drop_index('ix_aa_leu_notnull', table_name='aa', schema='nbs', postgresql_where=sa.text('leu IS NOT NULL'))
    op.drop_table('aa', schema='nbs')
    op.drop_index(op.f('ix_outbank_patient_id'), table_name='outbank', schema='main')
    op.drop_table('outbank', schema='main')
    op.drop_index(op.f('ix_opd_patient_id'), table_name='opd', schema='main')
    op.drop_table('opd', schema='main')
    op.drop_index(op.f('ix_msms_patient_id'), table_name='msms', schema='main')
    op.drop_table('msms', schema='main')
    op.drop_index(op.f('ix_enzyme_patient_id'), table_name='enzyme', schema='main')
    op.drop_table('enzyme', schema='main')
    op.drop_index(op.f('ix_dnabank_patient_id'), table_name='dnabank', schema='main')
    op.drop_table('dnabank', schema='main')
    op.drop_index(op.f('ix_biomarker_patient_id'), table_name='biomarker', schema='main')
    op.drop_index('ix_biomarker_lyso_high', table_name='biomarker', schema='main', postgresql_where=sa.text('dbs_lyso_gb3 > 5'))
    op.drop_table('biomarker', schema='main')
    op.drop_index(op.f('ix_aa_patient_id'), table_name='aa', schema='main')
    op.drop_index('ix_aa_leu_notnull', table_name='aa', schema='main', postgresql_where=sa.text('leu IS NOT NULL'))
    op.drop_table('aa', schema='main')
    op.drop_index(op.f('ix_outbank_patient_id'), table_name='outbank', schema='external')
    op.drop_table('outbank', schema='external')
    op.drop_index(op.f('ix_opd_patient_id'), table_name='opd', schema='external')
    op.drop_table('opd', schema='external')
    op.drop_index(op.f('ix_msms_patient_id'), table_name='msms', schema='external')
    op.drop_table('msms', schema='external')
    op.drop_index(op.f('ix_enzyme_patient_id'), table_name='enzyme', schema='external')
    op.drop_table('enzyme', schema='external')
    op.drop_index(op.f('ix_biomarker_patient_id'), table_name='biomarker', schema='external')
    op.drop_index('ix_biomarker_lyso_high', table_name='biomarker', schema='external', postgresql_where=sa.text('dbs_lyso_gb3 > 5'))
    op.drop_table('biomarker', schema='external')
    op.drop_index(op.f('ix_aa_patient_id'), table_name='aa', schema='external')
    op.drop_index('ix_aa_leu_notnull', table_name='aa', schema='external', postgresql_where=sa.text('leu IS NOT NULL'))
    op.drop_table('aa', schema='external')
    op.drop_index('ix_patient_name', table_name='patient', schema='nbs')
    op.drop_index('ix_patient_birthday', table_name='patient', schema='nbs')
    op.drop_table('patient', schema='nbs')
    op.drop_index('ix_patient_name', table_name='patient', schema='main')
    op.drop_index('ix_patient_birthday', table_name='patient', schema='main')
    op.drop_table('patient', schema='main')
    op.drop_index('ix_link_b', table_name='patient_link', schema='links')
    op.drop_table('patient_link', schema='links')
    op.drop_index('ix_patient_name', table_name='patient', schema='external')
    op.drop_index('ix_patient_birthday', table_name='patient', schema='external')
    op.drop_table('patient', schema='external')
    # ### end Alembic commands ###

    # 2. Drop trigger function and ENUM types (after every dependent table
    #    has been removed by the autogen block above).
    op.execute(DROP_SET_UPDATED_AT_FUNCTION)
    for stmt in DROP_ENUM_TYPES:
        op.execute(stmt)
    # NOTE: we intentionally don't DROP SCHEMA here — schemas may have been
    # created by setup-postgres.sh out-of-band, and other future migrations
    # may live in them. Dropping the database itself is the cleanest reset.
