"""ref_schema_lookups

Revision ID: 5a927e908e4a
Revises: baf340ba84fe
Create Date: 2026-04-30 06:13:57.659629
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from shared.models._ddl import (
    drop_trigger_set_updated_at_sql,
    trigger_set_updated_at_sql,
)

_REF_TABLES = ["aa_method_ref", "msms_method_ref", "enzyme_item_ref",
               "dna_item_ref", "command_phrase"]
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a927e908e4a'
down_revision: Union[str, Sequence[str], None] = 'baf340ba84fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aa_method_ref',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_aa_method_ref')),
    sa.UniqueConstraint('code', name='uq_aa_method_ref_code'),
    schema='ref'
    )
    op.create_table('command_phrase',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_phrase')),
    sa.UniqueConstraint('code', name='uq_command_phrase_code'),
    schema='ref'
    )
    op.create_table('dna_item_ref',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dna_item_ref')),
    sa.UniqueConstraint('code', name='uq_dna_item_ref_code'),
    schema='ref'
    )
    op.create_table('enzyme_item_ref',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enzyme_item_ref')),
    sa.UniqueConstraint('code', name='uq_enzyme_item_ref_code'),
    schema='ref'
    )
    op.create_table('msms_method_ref',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_msms_method_ref')),
    sa.UniqueConstraint('code', name='uq_msms_method_ref_code'),
    schema='ref'
    )
    # ### end Alembic commands ###

    for table in _REF_TABLES:
        op.execute(trigger_set_updated_at_sql("ref", table))


def downgrade() -> None:
    for table in reversed(_REF_TABLES):
        op.execute(drop_trigger_set_updated_at_sql("ref", table))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('msms_method_ref', schema='ref')
    op.drop_table('enzyme_item_ref', schema='ref')
    op.drop_table('dna_item_ref', schema='ref')
    op.drop_table('command_phrase', schema='ref')
    op.drop_table('aa_method_ref', schema='ref')
    # ### end Alembic commands ###
