"""etl_1_0_schema_additions

Revision ID: baf340ba84fe
Revises: f7a185a32e9a
Create Date: 2026-04-30 06:09:54.308414
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from shared.models._ddl import (
    drop_trigger_set_updated_at_sql,
    trigger_set_updated_at_sql,
)

# revision identifiers, used by Alembic.
revision: str = 'baf340ba84fe'
down_revision: Union[str, Sequence[str], None] = 'f7a185a32e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gcms',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('sample_name', sa.String(length=64), nullable=False),
    sa.Column('specimen_type', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=64), nullable=True),
    sa.Column('raw_data_path', sa.Text(), nullable=True),
    sa.Column('collect_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ntubiogene_sampleno', sa.String(length=64), nullable=True),
    sa.Column('v2_source_schema', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['main.patient.patient_id'], name=op.f('fk_gcms_patient_id_patient'), onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gcms')),
    schema='main'
    )
    op.create_index(op.f('ix_gcms_patient_id'), 'gcms', ['patient_id'], unique=False, schema='main')
    op.add_column('gag', sa.Column('od', sa.Numeric(precision=10, scale=3), nullable=True), schema='main')
    op.add_column('gag', sa.Column('urine_creatinine', sa.Numeric(precision=10, scale=3), nullable=True), schema='main')
    op.add_column('gag', sa.Column('mggag', sa.Numeric(precision=10, scale=3), nullable=True), schema='main')
    op.add_column('gag', sa.Column('twos', sa.Numeric(precision=10, scale=3), nullable=True), schema='main')
    op.add_column('gag', sa.Column('twos_cre', sa.Numeric(precision=10, scale=3), nullable=True), schema='main')
    op.add_column('patient', sa.Column('referring_doctor', sa.String(length=64), nullable=True), schema='main')
    # ### end Alembic commands ###

    op.execute(trigger_set_updated_at_sql("main", "gcms"))


def downgrade() -> None:
    op.execute(drop_trigger_set_updated_at_sql("main", "gcms"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'referring_doctor', schema='main')
    op.drop_column('gag', 'twos_cre', schema='main')
    op.drop_column('gag', 'twos', schema='main')
    op.drop_column('gag', 'mggag', schema='main')
    op.drop_column('gag', 'urine_creatinine', schema='main')
    op.drop_column('gag', 'od', schema='main')
    op.drop_index(op.f('ix_gcms_patient_id'), table_name='gcms', schema='main')
    op.drop_table('gcms', schema='main')
    # ### end Alembic commands ###
